# Generated by Django 5.2.8 on 2025-11-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnistory',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='alumnistory',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='alumnistory',
            name='topic',
        ),
        migrations.AddField(
            model_name='alumnistory',
            name='company',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumnistory',
            name='link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='alumnistory',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumnistory',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alumnistory',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
