# Generated by Django 5.2.8 on 2025-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_alumnistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnistory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_photos/'),
        ),
    ]
